# Generated by Django 3.1.1 on 2020-09-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(choices=[('R', 'RED'), ('O', 'ORANGE'), ('Y', 'YELLOW'), ('G', 'GREEN'), ('B', 'BLUE'), ('I', 'INDIGO'), ('V', 'VIOLET'), ('W', 'WHITE'), ('BL', 'BLACK')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shoetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('SNEAKER', 'SNEAKER'), ('BOOT', 'BOOT'), ('SANDAL', 'SANDAL'), ('DRESS', 'DRESS'), ('OTHER', 'OTHER')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=0)),
                ('brand_name', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=50)),
                ('fasten_type', models.CharField(max_length=50)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.shoecolor')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.manufacturer')),
                ('shoe_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoeapp.shoetype')),
            ],
        ),
    ]
