# Generated by Django 3.1.1 on 2020-09-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(),
        ),
    ]
